site_name: Portfolio
site_url: https://fabiuxx.github.io/portfolio/en
site_author: Fabio Antonio González Sosa
theme:
  name: gitbook
  custom_dir: ../overrides
extra_css:
  - page.css
# Deshabilita la busqueda: https://github.com/squidfunk/mkdocs-material/issues/1143#issuecomment-504640100
plugins: []
nav:
  - Home: index.md
  - Projects: projects.md
  - Contact: contact.md
