site_name: Portfolio
site_url: https://fabiuxx.github.io/portfolio
site_author: Fabio Antonio González Sosa
theme:
  name: gitbook
  custom_dir: overrides
# Deshabilita la busqueda: https://github.com/squidfunk/mkdocs-material/issues/1143#issuecomment-504640100
plugins: []
nav:
  - Home: index.md
